spring.application.name=library_borrow_and_book_tracking
spring.datasource.url=jdbc:mysql://localhost:3306/library_db
spring.datasource.username=root
<<<<<<< HEAD
<<<<<<< HEAD
spring.datasource.password=root
=======
spring.datasource.password=mle123960
>>>>>>> f9e8e42c54e67c53bd9033959d9deaa5aa8667be
=======
spring.datasource.password=root
>>>>>>> 53e183f6c1ffb69654c6ddc1f4727138eb71c6b5

# This will show you exactly what is happening during the save attempt
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable data initialization for now - we'll add data manually
spring.sql.init.mode=never

