 @startuml
!pragma teoz true

|User|
start
:Register / Login;
' =====================
' Main Home Page Loop
' =====================

    :Go to Home Page;

    ' User chooses action
    if (Choose Action?) then (Search)
        :Search Book;
    else (Scroll)
        :Scroll Book List;
    endif

    |System|
    if (Book Available?) then (Yes)

        if (Returned the old book?) then (No)
            :Reject Borrow;
            :Notify User to Return Book First;
            stop
        else (Yes)

            if (How many books?) then (book <= 3)
                |System|
                if (User Status = Blacklisted?) then (Yes)
                    :Reject Booking;
                    :Notify Punishment / Cannot Borrow;
                    stop
                else (Active)
                    ' =====================
                    ' Booking Stage
                    ' =====================
                    |User|
                    :Booking;

                    |System|
                    :Generate Receipt;

                    ' =====================
                    ' Both receive receipt (Booking)
                    ' =====================
                    fork
                        |User|
                        :Receive Receipt (Booked);
                    fork again
                        |Librarian|
                        :Receive Receipt (Booked);
                       
                    end fork

                    ' =====================
                    ' Borrowing Stage
                    ' =====================
                    |User|
                    :Come to Library to take book;

                    |Librarian|
                    :Search Receipt by User ID;
                    :Set Book Status (Borrowed);

                    |System|
                    :Set Return Date (starts now);
                endif

            else (book > 3)
                :Reject Borrow;
                :Notify Weekly Limit Reached;
                stop
            endif

        endif

    else (No)
        :Display "Book Unavailable";
        stop
    endif



' =====================
' RETURN FLOW
' =====================

|User|
:Return Book;

|Librarian|
:Process Return;
:Set Book Status to Returned;

|System|
if (Returned On Time?) then (Before day or On the day)
    :Record Ontime;
    :User Status = Active;
else (Late)
    :Record Late Return;
    if (User Late Count = 3times) then (Yes)
        :User Status = Blacklisted;
    else (No)
        :User Status = Active;
    endif
endif

' =====================
' LIBRARIAN MANAGEMENT TASKS
' =====================

|Librarian|
:Add Books;
:Remove Books;
:Update Books;

:Search User;
:View User Details;
:Edit User;
:Delete User;

:Update System Status;

stop
@enduml
